import { NavMenuType } from "./types/generic-types";

export const NavMenuTypeItems: NavMenuType[] = [
    {
        title: "Websites",
        link: "/websites",
    },
    {
        title: "Music",
        link: "/music",
    },
    {
        title: "Pricing",
        link: "/pricing",
    },
    {
        title: "Blog",
        link: "/blog",
    },
    {
        title: "Music",
        link: "/music",
    },
    {
        title: "About",
        link: "/About",
    },
];
export const NavMenuTypeAltItems: NavMenuType[] = [
    {
        title: "Contact Us",
        link: "/contact-us",
    },
    {
        title: "Schedule Your Free Consultation",
        link: "/contact-us",
    },
];

export const trackGenres = [
    "Afrobeats",
    "Alternative Hip Hop",
    "Alternative R&B",
    "Ambient",
    "Amapiano",
    "Bossa Nova",
    "Breakbeat",
    "Cinematic",
    "Christmas Music",
    "Contemporary R&B",
    "Classical",
    "Comedy",
    "Country",
    "Country Rock",
    "Dance",
    "Dancehall",
    "Deep House",
    "Disco",
    "Drum & Bass",
    "Drill",
    "Drumstep",
    "Dubstep",
    "EDM",
    "Electro Pop",
    "Electronic",
    "Emo",
    "Experimental",
    "Folk",
    "Funk",
    "Future Bass",
    "Gospel",
    "Hip Hop",
    "House",
    "Indie Pop",
    "Indie Rock",
    "Jazz",
    "Jazz Fusion",
    "Lo-Fi Hip Hop",
    "Movie Soundtrack",
    "Neo-Soul",
    "New Wave",
    "Pop",
    "Progressive House",
    "Psychedelic",
    "Punk",
    "R&B",
    "Rap",
    "Reggae",
    "Reggaeton",
    "Rock",
    "Soul",
    "Soundtrack",
    "Synth Pop",
    "Synthwave",
    "Tech House",
    "Techno",
    "Trap",
    "Trip Hop",
    "UK Drill",
    "Underground Hip Hop",
    "Vaporwave",
    "World Music",
];

export const ReferralSources = ["Card From Brite", "Magazine", "Google", "Facebook", "Word of Mouth", "Other"];

export const Plans = ["Studio Basic", "Studio Plus", "Studio Pro", "Studio Commerce"];

export const bannedWords = [
    "sex",
    "porn",
    "fuck",
    "shit",
    "bitch",
    "dick",
    "pussy",
    "asshole",
    "cunt",
    "nigger",
    "fag",
    "whore",
    "slut",
    "rape",
    "cum",
    "cock",
    "boob",
    "tit",
    "twat",
    "wank",
    "jerk",
    "suck",
    "blowjob",
    "handjob",
    "anal",
    "vagina",
    "penis",
    "masturbate",
    "orgasm",
    "hentai",
    "milf",
    "gay",
    "lesbian",
    "trans",
    "tranny",
    "retard",
    "dyke",
    "queer",
    "chink",
    "gook",
    "spic",
    "wetback",
    "kike",
    "coon",
    "negro",
    "jap",
    "paki",
    "orgy",
    "fisting",
    "rimjob",
    "felch",
    "scat",
    "bestiality",
    "zoophile",
    "necrophilia",
    "incest",
    "bdsm",
    "bondage",
    "dominatrix",
    "submissive",
    "escort",
    "prostitute",
    "hooker",
    "callgirl",
    "gigolo",
    "stripper",
    "camgirl",
    "camwhore",
    "escortservice",
    "heilhitler",
    "nazis",
    "hitler",
    "kkk",
    "islamophobe",
    "antisemite",
    "terrorist",
    "islamicterrorist",
    "jihadist",
    "shemale",
    "he-she",
    "ladyboy",
    "gimp",
    "deafie",
    "blindie",
    "redskin",
    "injun",
    "whitey",
    "honky",
    "tits",
    "boobs",
    "ballsack",
    "nutsack",
    "testicle",
    "scrotum",
    "clit",
    "clitoris",
    "labia",
    "pubes",
    "pubic",
    "erection",
    "ejaculate",
    "jizz",
    "spooge",
    "skeet",
    "nut",
    "orgasmic",
    "pornstar",
    "pornhub",
    "redtube",
    "xvideos",
    "xnxx",
    "brazzers",
];
