import { ITrackProps, NavMenuType } from "./types";

export const NavMenuTypeItems: NavMenuType[] = [
    {
        title: "Websites",
        link: "/websites",
    },
    {
        title: "Music",
        link: "/music",
    },
    {
        title: "Pricing",
        link: "/pricing",
    },
    {
        title: "Blog",
        link: "/blog",
    },
    {
        title: "Music",
        link: "/music",
    },
    {
        title: "About",
        link: "/About",
    },
];
export const NavMenuTypeAltItems: NavMenuType[] = [
    {
        title: "Contact Us",
        link: "/contact-us",
    },
    {
        title: "Schedule Your Free Consultation",
        link: "/contact-us",
    },
];

export const ReferralSources = ["Card From Brite", "Magazine", "Google", "Facebook", "Word of Mouth", "Other"];

export const Plans = ["Studio Basic", "Studio Plus", "Studio Pro", "Studio Commerce"];

export const dummyMusic: ITrackProps[] = [
    {
        id: "1",
        album_id: "1",
        artist_id: "1",
        title: "Sample Track",
        artists: [],
        credits: [],
        url: "https://example.com/track.mp3",
        album: {
            id: "1",
            artist_id: "1",
            name: "Sample Album",
            type: "Album",
            release_date: "2024-01-01",
            created_at: "2024-01-01T00:00:00Z",
            updated_at: "2024-01-01T00:00:00Z",
            images: [],
        },
        type: "Unreleased",
        locked: false,
        is_liked: false,
        duration: 180, // duration in seconds
        release_date: "2024-01-01",
        genre: "Pop",
        plays: 0,
    },
];

export const bannedWords = [
    "sex",
    "porn",
    "fuck",
    "shit",
    "bitch",
    "dick",
    "pussy",
    "asshole",
    "cunt",
    "nigger",
    "fag",
    "whore",
    "slut",
    "rape",
    "cum",
    "cock",
    "boob",
    "tit",
    "twat",
    "wank",
    "jerk",
    "suck",
    "blowjob",
    "handjob",
    "anal",
    "vagina",
    "penis",
    "masturbate",
    "orgasm",
    "hentai",
    "milf",
    "gay",
    "lesbian",
    "trans",
    "tranny",
    "retard",
    "dyke",
    "queer",
    "chink",
    "gook",
    "spic",
    "wetback",
    "kike",
    "coon",
    "negro",
    "jap",
    "paki",
    "orgy",
    "fisting",
    "rimjob",
    "felch",
    "scat",
    "bestiality",
    "zoophile",
    "necrophilia",
    "incest",
    "bdsm",
    "bondage",
    "dominatrix",
    "submissive",
    "escort",
    "prostitute",
    "hooker",
    "callgirl",
    "gigolo",
    "stripper",
    "camgirl",
    "camwhore",
    "escortservice",
    "heilhitler",
    "nazis",
    "hitler",
    "kkk",
    "islamophobe",
    "antisemite",
    "terrorist",
    "islamicterrorist",
    "jihadist",
    "shemale",
    "he-she",
    "ladyboy",
    "gimp",
    "deafie",
    "blindie",
    "redskin",
    "injun",
    "whitey",
    "honky",
    "tits",
    "boobs",
    "ballsack",
    "nutsack",
    "testicle",
    "scrotum",
    "clit",
    "clitoris",
    "labia",
    "pubes",
    "pubic",
    "erection",
    "ejaculate",
    "jizz",
    "spooge",
    "skeet",
    "nut",
    "orgasmic",
    "pornstar",
    "pornhub",
    "redtube",
    "xvideos",
    "xnxx",
    "brazzers",
];
