export const QUERY_KEYS = {
    profiles: ["public", "profiles"] as const,
    tracks: ["music", "tracks"] as const,
    albums: ["music", "albums"] as const,
    album_images: ["music", "album_images"] as const,
    artist_verifications: ["music", "artist_verifications"] as const,
    artists: ["music", "artists"] as const,
    download_links: ["music", "download_links"] as const,
    invites: ["music", "invites"] as const,
    track_credits: ["music", "track_credits"] as const,
    track_likes: ["music", "track_likes"] as const,
    remixes: ["music", "remixes"] as const,
    playlists: ["music", "playlists"] as const,
    playlist_tracks: ["music", "playlist_tracks"] as const,
    playlist_likes: ["music", "playlist_likes"] as const,
} as const;
